server:
  port: 8080
spring:
  application:
    name: PlayHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3305/play_hub?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6378
      database: 1
  rabbitmq:
    host: 127.0.0.1 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /luke # 虚拟主机
    username: luke # 用户名
    password: 1234 # 密码
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启连接超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: none # 消息是否到达交换机，开启publisher confirm机制，并设置confirm类型
    publisher-returns: off # 消息成功到达交换机，但无法路由到任何队列

mybatis:
  # 配置 mapper.xml 映射文件路径（如果用 XML 方式写 SQL）
  mapper-locations: classpath:mapper/*.xml  # 例如：src/main/resources/mapper/ 下的所有 .xml 文件
  # 配置实体类包路径（可选，用于别名映射，简化 XML 中的类名）
  type-aliases-package: com.luke.playhub.entity  # 实体类所在包
  # 开启驼峰命名转换（例如：数据库字段 user_name → 实体类属性 userName）
  configuration:
    map-underscore-to-camel-case: true
    # 打印 SQL 日志（开发环境可选，方便调试）
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.luke: warn
  pattern:
    dateformat: HH:mm:ss:SSS
